### ISSUE TITLE
Failed to start the download. Unauthorized.

### ISSUE THREAD

**Issue by Rajwadkar07** [out386/aria-telegram-mirror-bot#38]
I am facing this issue. I checked everything. My aria_secret is same in .constants.js and aria.sh. Please guide me for a fix?

**Comment by out386** [comment]
The only reason this happens is because of mismatched secret.

Make sure that the secret is in `./src/.constants.js`, not in `./out/.constants.js`

Run `tsc` after putting the secret in

Run
```killall aria2c && killall aria2
./aria.sh
npm start```

If even this fails, check aria_secret yet again, and reboot the computer, and make sure that nothing else is starting an aria rpc.

**Comment by Rajwadkar07** [comment]
thanks it worked :)

**Comment by vivekgajjar** [comment]
Not working
