### ISSUE TITLE
Logs & zip & Authentication 

### ISSUE THREAD

**Issue by punk99** [out386/aria-telegram-mirror-bot#95]
Could You Add a command or feature that returns logs
and also the ability to zip files

**Comment by out386** [comment]
I won't add a zip option, because it can already archive to tar instead.
The logs are directly sent to STDOUT and STDERR, as is common practice. This allows logging to happen even as the bot crashes, and means that the bot itself doesn't have access to logs. I'm not planning to have separate log files.

So if you need the logs, you'll have to use something else to monitor them.
As a starting point, to get the logs :
If you're using tmux, there's a plugin to store logs, or you can just redirect the streams to a file. With systemd, you can manage logs with `journalctl`.
